project_id = "emscfiinctuysscrarlg"

[functions.generate-pdf]
verify_jwt = true

[functions.send-notification]
verify_jwt = true

[functions.invite-team-member]
verify_jwt = false

[functions.customer-portal-auth]
verify_jwt = false

[functions.create-invoice-payment]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.send-payment-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.weekly-digest]
verify_jwt = false
