project_id = "emscfiinctuysscrarlg"

[functions.generate-pdf]
verify_jwt = true

[functions.send-notification]
verify_jwt = false

[functions.invite-team-member]
verify_jwt = true

[functions.customer-portal-auth]
verify_jwt = false
